name: 'bytebase release api sample'
description: 'Use Bytebase API to create releases and update databases'
author: 'p0ny'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  bb-token:
    description: 'The Bytebase access token'
    required: true
  gh-token:
    description: 'The github access token'
    required: true

# Define your outputs here.
outputs:
  release-url:
    description: 'The created Bytebase release URL'
  rollout-url:
    description: 'The created Bytebase rollout URL'

runs:
  using: node20
  main: dist/index.js
