name: Bytebase cicd

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  bytebase-cicd:
    runs-on: ubuntu-latest
    env:
      BYTEBASE_URL: "https://df5e-185-220-236-33.ngrok-free.app"
      BYTEBASE_SERVICE_ACCOUNT: "xz@bytebase.com"
      BYTEBASE_PROJECT: "db333"
    name: Bytebase cicd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Bytebase
        id: login
        uses: ./.github/actions/bytebase-login
        with:
          url: ${{ env.BYTEBASE_URL }}
          service-account: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-account-key: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: create release
        uses: ./.github/actions/bytebase-cicd
        with:
          dir: "/migrations/"
          bb-token: ${{ steps.login.output.token }}
          bb-url: ${{ env.BYTEBASE_URL }}
          bb-project: ${{ env.BYTEBASE_PROJECT }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
