name: Bytebase cicd

on:
  push:
    branches:
      - main
jobs:
  bytebase-cicd:
    runs-on: ubuntu-latest
    env:
      BYTEBASE_URL: "https://bytebase-ci.zeabur.app"
      BYTEBASE_SERVICE_ACCOUNT: "ci@service.bytebase.com"
      PROJECT: "example"
      ISSUE_TITLE: "[${{ github.repository }}#${{ github.event.pull_request.number }}] ${{ github.event.pull_request.title }}"
    name: Bytebase cicd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: printkk
        uses: ./.github/actions/bytebase-cicd
        with:
          dir: "/"
      - name: Login to Bytebase
        id: login
        uses: ./.github/actions/bytebase-login
        with:
          url: ${{ env.BYTEBASE_URL }}
          service-account: ${{ env.BYTEBASE_SERVICE_ACCOUNT }}
          service-account-key: ${{ secrets.BYTEBASE_PASSWORD }}
      - name: Check Issue Status
        id: check
        uses: ./.github/actions/check-issue-status
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          dir: "/"
          pattern: "**/*.up.sql"
          url: ${{ env.BYTEBASE_URL }}
          token: ${{ steps.login.outputs.token }}
          headers: '{"Accept-Encoding": "deflate, gzip"}'
          project-id: ${{ env.PROJECT }}
          title: ${{ env.ISSUE_TITLE }}